/**
 * ADUC's "Copy…": a new account from a template account.
 *
 * The template decides where the account goes and what it is given — OU,
 * groups, department, paths; this dialog asks who the person is and how they
 * sign in the first time. The password is generated by default and shown once,
 * after the account exists, together with anything that could not be done:
 * the dialog does not close on success, because what it has to say then is
 * the one thing that cannot be looked up later.
 */

import { useMutation, useQuery } from '@tanstack/react-query'
import { useEffect, useState, type FormEvent } from 'react'

import { ApiError } from '../../api/client'
import { api } from '../../api/endpoints'
import type { CopyUserResult } from '../../api/types'
import { UserIdentityFields, useUserIdentity } from '../../components/dialogs'
import {
  CopyButton,
  ErrorMessage,
  Field,
  Modal,
  Spinner,
  TextRow,
} from '../../components/primitives'
import { nameFromDn, parentDn } from '../../dn'
import { useI18n } from '../../i18n'
import { requestedGroups } from './copyUser'

export function CopyUserDialog({
  template,
  onClose,
  onDone,
}: {
  template: { dn: string; name: string }
  onClose: () => void
  onDone: (message: string) => void
}) {
  const { t, te } = useI18n()
  const identity = useUserIdentity()
  const source = useQuery({
    queryKey: ['copy-template', template.dn],
    queryFn: () => api.user(template.dn),
  })
  const offered = useQuery({
    queryKey: ['copy-template-groups', template.dn],
    queryFn: () => api.copyTemplateGroups(template.dn),
  })
  const [generate, setGenerate] = useState(true)
  const [password, setPassword] = useState('')
  const [mustChange, setMustChange] = useState(true)
  const [enabled, setEnabled] = useState(true)
  const [leftOut, setLeftOut] = useState<Set<string>>(new Set())
  const [error, setError] = useState<unknown>(null)
  const [result, setResult] = useState<CopyUserResult | null>(null)

  // The UPN suffix comes from the template, as in ADUC, until one is chosen.
  const templateUpn = source.data?.attributes.upn
  const { setForm } = identity
  useEffect(() => {
    if (typeof templateUpn !== 'string' || !templateUpn.includes('@')) return
    const suffix = templateUpn.slice(templateUpn.lastIndexOf('@') + 1)
    setForm((current) => (current.upnSuffix ? current : { ...current, upnSuffix: suffix }))
  }, [templateUpn, setForm])

  const templateGroups = offered.data?.groups ?? []
  const groups = templateGroups.map((group) => group.dn)
  const target = parentDn(template.dn)

  const create = useMutation({
    mutationFn: () =>
      api.copyUser(template.dn, {
        sam_account_name: identity.form.sam.trim(),
        common_name: identity.commonName,
        attributes: identity.attributes,
        ...(generate ? { generate_password: true } : { password: password || undefined }),
        must_change_password: mustChange,
        enabled,
        groups: requestedGroups(groups, leftOut),
      }),
    onSuccess: (created) => {
      setError(null)
      setResult(created)
    },
    onError: setError,
  })

  const submit = (event: FormEvent) => {
    event.preventDefault()
    create.mutate()
  }

  // Closing after the account exists is finishing, however the dialog is closed.
  const close = () => {
    if (result) onDone(t('status.created', { name: result.user.name }))
    onClose()
  }

  const toggle = (group: string) =>
    setLeftOut((current) => {
      const next = new Set(current)
      const key = group.toLowerCase()
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })

  if (result) {
    return (
      <Modal
        title={t('copy.title', { name: template.name })}
        onClose={close}
        footer={
          <button type="button" className="button button--primary" onClick={close}>
            {t('copy.done')}
          </button>
        }
      >
        <div className="form">
          <p>{t('status.created', { name: result.user.name })}</p>
          {result.generated_password && (
            <>
              <Field label={t('copy.generatedPassword')} hint={t('copy.generatedPasswordHint')}>
                <div className="bitlocker__secret">
                  <span className="mono selectable">{result.generated_password}</span>
                  <CopyButton value={result.generated_password} />
                </div>
              </Field>
            </>
          )}
          {result.groups_added.length > 0 && (
            <TextRow
              label={t('detail.memberOf')}
              value={result.groups_added.map(nameFromDn).join(', ')}
            />
          )}
          {result.failed_groups.length > 0 && (
            <div className="alert alert--warning">
              <p>{t('copy.failedGroups')}</p>
              <ul>
                {result.failed_groups.map((failure) => (
                  <li key={failure.dn} title={failure.dn}>
                    <strong>{nameFromDn(failure.dn)}</strong>
                    {failure.primary && ` (${t('copy.primaryGroup')})`}:{' '}
                    {te(new ApiError(0, { code: failure.code ?? '', message: failure.message }))}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </Modal>
    )
  }

  return (
    <Modal
      title={t('copy.title', { name: template.name })}
      onClose={onClose}
      footer={
        <>
          <button type="button" className="button" onClick={onClose}>
            {t('action.cancel')}
          </button>
          <button
            type="submit"
            form="copy-user"
            className="button button--primary"
            disabled={create.isPending || !source.data || !offered.data}
          >
            {t('action.create')}
          </button>
        </>
      }
    >
      <form id="copy-user" onSubmit={submit} className="form">
        <ErrorMessage error={error ?? source.error ?? offered.error} onDismiss={() => setError(null)} />
        <TextRow label={t('copy.target')} value={<span title={target}>{nameFromDn(target)}</span>} />
        <UserIdentityFields identity={identity} />

        <fieldset className="radio-group radio-group--block">
          <legend>{t('login.password')}</legend>
          <label className="checkbox">
            <input type="radio" name="password-mode" checked={generate} onChange={() => setGenerate(true)} />
            <span>{t('copy.generate')}</span>
          </label>
          <label className="checkbox">
            <input type="radio" name="password-mode" checked={!generate} onChange={() => setGenerate(false)} />
            <span>{t('copy.ownPassword')}</span>
          </label>
          {!generate && (
            <input
              type="password"
              autoComplete="new-password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          )}
        </fieldset>
        <label className="checkbox">
          <input type="checkbox" checked={mustChange} onChange={(e) => setMustChange(e.target.checked)} />
          <span>{t('dialog.passwordMustChange')}</span>
        </label>
        <label className="checkbox">
          <input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} />
          <span>{t('user.status.active')}</span>
        </label>

        <fieldset className="radio-group radio-group--block">
          <legend>{t('copy.groups')}</legend>
          {offered.isPending ? (
            <Spinner />
          ) : templateGroups.length === 0 ? (
            <p className="muted small">{t('copy.noGroups')}</p>
          ) : (
            templateGroups.map((group) => (
              <label key={group.dn} className="checkbox" title={group.dn}>
                <input
                  type="checkbox"
                  checked={!leftOut.has(group.dn.toLowerCase())}
                  onChange={() => toggle(group.dn)}
                />
                <span>
                  {nameFromDn(group.dn)}
                  {group.primary && <span className="muted"> ({t('copy.primaryGroup')})</span>}
                </span>
              </label>
            ))
          )}
        </fieldset>
        <p className="muted small">{t('copy.carriesOver')}</p>
      </form>
    </Modal>
  )
}
